core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include('users.urls'), name="users"),
    path("", include('movies.urls'), name="home"),
    path("", include('tv_series.urls'), name="home"),
    path("api/", include('movies.api.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

movies/api/urls.py
from django.urls import path
from .views import *

app_name = "products_api"

urlpatterns = [
    path("movies/", MovieList.as_view(), name="movie-list"),
    path("create/", MovieCreate.as_view(), name="create"),
    path("detail/<slug>/", movies_detail, name="detail"),
]

movies/urls.py
from django.urls import path
from .views import *

app_name = "movies"


urlpatterns = [
    path("",show_home, name="home"),
    path("movies/",show_list, name="movies"),
    path("movies-detail/<slug>/",movie_details, name="movies-detail"),
    path('delete-comment/', delete_comment, name='delete_comment'),
    path("movie-wish/",movie_wish_view, name="movie-wish"),
    path("wishlist/",wishlist_view, name="wishlist"),
    path("movie-serie/",movie_serie, name="movie-serie"),
    path('like-movie/<int:comment_id>/',like_comment, name='like_comment'),
    path('dislike-movie/<int:comment_id>/',dislike_comment, name='dislike_comment'),
    
    
]

tv_series/urls.py
from django.urls import path
from .views import *

app_name = "series"


urlpatterns = [
    path("series/",show_list_series, name="series"),
    path("serie-wish/",serie_wish_view, name="serie-wish"),
    path("series-detail/<slug>/",serie_detail, name="series-detail"),
    path("series-episode/",serie_episode, name="series-episode"),
    path('delete-comments/', delete_comment, name='delete_comments'),
    path('delete-commentss/', delete_comments, name='delete_commentss'),
    path('like-serie/<int:comment_id>/',like_comment, name='like_serie_comment'),
    path('dislike-serie/<int:comment_id>/',dislike_comment, name='dislike_serie_comment'),
    path('like-episode-serie/<int:comment_id>/',like_episode_comment, name='like_serie_comment'),
    path('dislike-episode-serie/<int:comment_id>/',dislike_episode_comment, name='dislike_serie_comment'),
]

movies/models.py
from django.db import models

from services.mixin import SlugMixin, DateMixin
from services.slugify import slugify
from services.generator import CodeGenerator
from services.uploader import Uploader
from services.choiches import account

from ckeditor.fields import RichTextField

from django.db import models
from django.contrib.auth import get_user_model



# Create your models here.
User = get_user_model()

class Country(DateMixin):
    name = models.CharField(max_length=255,blank=True,null=True)

    class Meta:
        verbose_name = 'Ölkə'
        verbose_name_plural = 'Ölkə'

    def __str__(self):
        return self.name

class Genre(DateMixin):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Janr'
        verbose_name_plural = 'Janr'

    def __str__(self):
        return self.name

class Language(DateMixin):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Dil'
        verbose_name_plural = 'Dillər'

    def __str__(self):
        return self.name

class Actor(DateMixin):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birth_date = models.DateField()

    class Meta:
        verbose_name = 'Aktyor'
        verbose_name_plural = 'Aktyorlar'

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Movie(SlugMixin,DateMixin):
    title = models.CharField(max_length=255)
    director = models.CharField(max_length=255)
    description = RichTextField()
    account = models.CharField(max_length=30,choices=account,default='Basic')
    release_date = models.DateField()
    running_time = models.PositiveIntegerField()
    age_limit = models.PositiveIntegerField(blank=True,null=True)
    language = models.ManyToManyField(Language)
    imdb = models.FloatField()
    genres = models.ManyToManyField(Genre)
    actors = models.ManyToManyField(Actor)
    country = models.ForeignKey(Country, on_delete=models.PROTECT,blank=True,null=True)
    trailer = models.URLField(blank=True, null=True)
    poster = models.ImageField(upload_to='posters/')
    wishlist = models.ManyToManyField(User, blank=True)
    watched_count = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Film'
        verbose_name_plural = 'Filmlər'
    

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.code = CodeGenerator.create_slug_shortcode(
            size=20, model_=Movie
        )
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Review(DateMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 11)])
    title = models.TextField(default="null")
    text = RichTextField(default="null")
    

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'
    

    def __str__(self):
        return f'{self.user.username} - {self.movie.title}'


class Comment(DateMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    comment = RichTextField()
    likes = models.ManyToManyField(User, related_name='liked_comments', blank=True)
    dislikes = models.ManyToManyField(User, related_name='disliked_comments', blank=True)  

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Commentlər'

    def __str__(self):
        return f'{self.user.username} - {self.movie.title}'

    def can_delete(self, user):
        return self.user == user
    






class ComingMovie(DateMixin):
    title = models.CharField(max_length=200)
    release_date = models.DateField()
    genres = models.ManyToManyField(Genre)
    poster = models.ImageField(upload_to='posters/')

    class Meta:
        verbose_name = 'Gələcək Filmlər'
        verbose_name_plural = 'Gələcək Filmlər'

    def __str__(self):
        return self.title

        




class MovieGalleryVideo(DateMixin):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    video = models.FileField(upload_to=Uploader.upload_video_movies)

    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Videolar'

    def __str__(self):
        return self.movie.title


class MovieGalleryImage(DateMixin):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=Uploader.upload_image_movies)

    class Meta:
        verbose_name = 'Şəkil'
        verbose_name_plural = 'Şəkillər'

    def __str__(self):
        return self.movie.title
    

movies/forms.py
from django import forms
from .models import Comment, Review

class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={ 
        'placeholder':'Rəy Bildir',
        'rows' : '2',
        'style': ' text-align:left; padding:50px 40px; background-color:#2b2b31; border-radius: 4px; border: 1px; color: #fff; font-size: 16px; width: 100%;',
    }))
    
    class Meta:
        model = Comment
        fields = ('comment',)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'text', 'title']

movies/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from ..models import Movie
from .serializers import MovieSerializer,MovieCreateSerializer
from django.shortcuts import get_object_or_404
from rest_framework import generics

@api_view()
def hello_world(request):
    movies = Movie.objects.all()
    serializers = MovieSerializer(movies,many=True)

    return Response(serializers.data)

@api_view()
def movies_detail(request,slug):
    movie = get_object_or_404(Movie,slug=slug)
    serializers = MovieSerializer(movie)
    return Response(serializers.data)

class MovieList(generics.ListAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

class MovieCreate(generics.CreateAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieCreateSerializer

movies/views.py
from django.shortcuts import render,redirect    
from .models import *
from tv_series.models import Serie
from users.models import MyUser
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.db.models import Count,Avg,Q
from django.db.models.functions import ExtractYear
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import CommentForm,ReviewForm
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.urls import reverse

User = get_user_model()

def show_home(request):
    trends=Movie.objects.annotate(user_count=Count('wishlist')).order_by('-user_count')[:20]
    imdb = Movie.objects.order_by('-imdb')[:6]
    movies=Movie.objects.all()
    new_movies=Movie.objects.order_by('-created_at')[:6]
    series=Serie.objects.all()
    new_series = Serie.objects.order_by('-created_at')[:6]
    users=User.objects.all()
    coming_movies = ComingMovie.objects.order_by('-release_date')[:6]

    search1=request.GET.get('search')
    if search1:
        movies = Movie.objects.filter(title__icontains=search1)

    

    context = {
        'coming_movies':coming_movies,
        'movies':movies,
        'new_movies' : new_movies,
        'series':series,
        'new_series': new_series,
        'trends':trends,
        'users':users,
        'imdb': imdb,
        
        
    }

    return render(request, 'movies/home.html',context)



def show_list(request):
    genres = request.GET.getlist('genre', None)
    language = request.GET.getlist('language', None)
    years = request.GET.get('years', None)
    imdb = request.GET.get('imdb', None)
    


    coming_movies = ComingMovie.objects.order_by('-release_date')[:6]
    movies = Movie.objects.all()
    if genres:
        movies = movies.filter(genres__in=genres).distinct()
    if language:
        movies = movies.filter(language__in=language).distinct()
    
    if years:
        start_year, end_year = years.split(',')
        movies = movies.filter(release_date__year__range=(start_year, end_year))

    




    if imdb:
        imdb_start, imdb_end = imdb.split(',')
        movies = movies.filter(imdb__range=(float(imdb_start), float(imdb_end)))
    
    search1=request.GET.get('search')
    if search1:
        movies = Movie.objects.filter(title__icontains=search1)
        
    

    paginator = Paginator(movies, 12)
    page = request.GET.get('page', 1)
    movies_list = paginator.get_page(page)
    context = {
        'coming_movies':coming_movies,
        'movies': movies_list,
        'genres': Genre.objects.all(),
        'language': Language.objects.all(),
        
    }
    return render(request, 'movies/movie_list.html', context)



def premium_user(view_func):
    def wrap(request, *args, **kwargs):
        slug = kwargs.get('slug')
        movie = get_object_or_404(Movie, slug=slug)

        if movie.account != 'Premium' and (not request.user.is_authenticated or request.user.account != 'Premium'):
            return view_func(request, *args, **kwargs)

        elif movie.account == 'Premium' and (not request.user.is_authenticated or request.user.account != 'Premium'):
            if request.user.is_authenticated:
                messages.warning(request, 'Bu filmə baxmaq üçün premium hesabınız olmalıdır!')
                return redirect('users:plan')
            else:
                login_url = reverse('users:login')
                redirect_url = login_url + '?next=' + request.path
                return redirect(redirect_url)

        else:
            return view_func(request, *args, **kwargs)

    return wrap


@premium_user
def movie_details(request, slug):
    movie = get_object_or_404(Movie, slug=slug)
    session_key = f'viewed_movie_{movie.id}'
    if not request.session.get(session_key, False):
        movie.watched_count += 1
        movie.save()
        request.session[session_key] = True

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        review_form = ReviewForm(request.POST)

        if not request.user.is_authenticated: 
            return redirect('users:login')  

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
            return redirect('movies:movies-detail', slug=slug)
        elif review_form.is_valid():
            review = review_form.save(commit=False)
            review.movie = movie
            review.user = request.user
            review.save()
            return redirect('movies:movies-detail', slug=slug)
    else:
        comment_form = CommentForm()
        review_form = ReviewForm()

    comments = Comment.objects.filter(movie=movie).order_by('-created_at')
    trends = Movie.objects.annotate(user_count=Count('wishlist')).order_by('-user_count')[:20]
    reviews = Review.objects.filter(movie=movie).order_by('-created_at')
    average_rating = Review.objects.filter(movie=movie).aggregate(Avg('rating'))
    if average_rating['rating__avg']:
        average_rating = round(average_rating['rating__avg'], 1)

    return render(request, 'movies/movie_detail.html', {'movie': movie, 'comment_form': comment_form,'average_rating': average_rating,'reviews': reviews, 'review_form': review_form, 'comments': comments, 'trends': trends})


@login_required
def like_comment(request, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    liked = request.POST.get("liked") == "true"
    
    if liked:
        comment.likes.remove(request.user)
    else:
        comment.likes.add(request.user)
        comment.dislikes.remove(request.user)
    
    data = {"likes": comment.likes.count(), "dislikes": comment.dislikes.count()}
    return JsonResponse(data)

@login_required
def dislike_comment(request, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    disliked = request.POST.get("disliked") == "true"
    
    if disliked:
        comment.dislikes.remove(request.user)
    else:
        comment.dislikes.add(request.user)
        comment.likes.remove(request.user)
    
    data = {"likes": comment.likes.count(), "dislikes": comment.dislikes.count()}
    return JsonResponse(data)


@login_required
@require_POST
def delete_comment(request):
    comment_id = request.POST.get('comment_id')
    comment = get_object_or_404(Comment, id=comment_id, user=request.user)
    comment.delete()
    return JsonResponse({'success': True})



def movie_wish_view(request):
    data = {}
    movie = get_object_or_404(Movie, id=int(request.POST.get("id")))
    

    if request.user in movie.wishlist.all():
        movie.wishlist.remove(request.user)
        data["success"] = False
    else:
        movie.wishlist.add(request.user)
        data["success"] = True
    
    return JsonResponse(data)



def wishlist_view(request):
    coming_movies = ComingMovie.objects.order_by('-release_date')[:6]
    movies = Movie.objects.filter(
        wishlist__in=[request.user] ).order_by('-created_at')

    series = Serie.objects.filter(
        wishlist__in=[request.user] ).order_by('-created_at')

    
    

    context = {
        'series': series,
        'movies' : movies,
        'coming_movies':coming_movies,
    }

    return render(request, 'movies/wishlist.html',context)




def movie_serie(request):
    movies = Movie.objects.all()
    series = Serie.objects.all()
    coming_movies = ComingMovie.objects.order_by('-release_date')[:6]

    search = request.GET.get('search')
    if search:
        movies = Movie.objects.filter(title__icontains=search)
        series = Serie.objects.filter(title__icontains=search)
        

   
    context = {
        'coming_movies' : coming_movies,
        'series': series,
        'movies' : movies,
    }
    return render(request, 'movies/search.html', context)

templates/movies/search.html
{% extends 'base.html' %}
{% block body %}


<!-- page title -->
<section class="section section--first section--bg" data-bg="/static/assets/img/section/section.jpg">
	{% csrf_token %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="section__wrap">
					<!-- section title -->
					<h1 class="section__title">Axtarış Nəticələri</h1>
					<!-- end section title -->

					<!-- breadcrumb -->
					<ul class="breadcrumb">
						<li class="breadcrumb__item"><a href="index.html">Ana Səhifə</a></li>
						<li class="breadcrumb__item breadcrumb__item--active">Axtarış Nəticələri</li>
					</ul>
					<!-- end breadcrumb -->
				</div>
			</div>
		</div>
	</div>
</section>
<!-- end page title -->



<!-- catalog -->
<div class="catalog">
	<div class="container">
		<div class="row row--grid">
			<!-- card -->
			{% for movie in movies %}
			<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
				<div class="card">
					<a href="{% url 'movies:movies-detail' movie.slug %}" class="card__cover">
						<img src="{{movie.poster.url}}" alt="" width="210" height="250">
						<span class="card__play">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg>
						</span>
					</a>
					<div class="card__content">
						
						<h3 class="card__title"><a href="#">{{movie.title}}</a></h3>
						
					
						
						<span class="card__category" style="font-weight: bold;margin-top: -3px;">
							{% for genre in  movie.genres.all %}
									<a href="#">{{genre.name}}</a>
							{% endfor %}
							
						</span>
						
					<span style="color: rgb(227, 74, 74); font-weight: bolder;" ><span style="color: blueviolet; font-weight: bold;"> IMDb</span> {{movie.imdb}}</span>
					<span style="color: #753750; font-weight: bold;">{{movie.release_date|date:'Y'}}</span>

					{% if user.is_authenticated %}
					<a onclick="getWish('{{movie.id}}')" class="notifi-wishlist">
						<i  class="fa fa-heart heart-icon" id="trend-heart-{{movie.id}}"
						{% if request.user in movie.wishlist.all %} style=color:green; 	
						{% else %} style=color:red;
						{% endif %}>
						</i>
					</a>
					{% endif %}
				  
				</div>

				</div>
			</div>
			{% endfor %}
			<!-- end card -->

            {% for serie in series %}
			<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
				<div class="card">
					<a href="{% url 'series:series-detail' serie.slug %}" class="card__cover">
						<img src="{{serie.poster.url}}" alt="" width="210" height="250">
						<span class="card__play">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg>
						</span>
					</a>
					<div class="card__content">
						
						<h3 class="card__title"><a href="#">{{serie.title}}</a></h3>
						
					
						
						<span class="card__category" style="font-weight: bold;margin-top: -3px;">
							{% for genre in  serie.genres.all %}
									<a href="#">{{genre.name}}</a>
							{% endfor %}
							
						</span>
						
					<span style="color: rgb(227, 74, 74); font-weight: bolder;" ><span style="color: blueviolet; font-weight: bold;"> IMDb</span> {{serie.imdb}}</span>
					<span style="color: #753750; font-weight: bold;">{{serie.release_date|date:'Y'}}</span>

					{% if user.is_authenticated %}
					<a onclick="getWishd('{{serie.id}}')" class="notifi-wishlist">
						<i  class="fa fa-heart heart-icon" id="serie-heart-{{serie.id}}"
						{% if request.user in serie.wishlist.all %} style=color:green; 	
						{% else %} style=color:red;
						{% endif %}>
						</i>
					</a>
					{% endif %}
				  
				</div>

				</div>
			</div>
			{% endfor %}

		</div>

		
	</div>
</div>
<!-- end catalog -->























<!-- expected premiere -->
<section class="section section--bg" data-bg="/static/assets/img/section/section.jpg">
	<div class="container">
		<div class="row">
			<!-- section title -->
			<div class="col-12">
				<h2 class="section__title">Yaxın Zamanda Gələcək Filmlər</h2>
			</div>
			<!-- end section title -->
		</div>

		<div class="row row--grid">
			<!-- card -->
			{% for coming_movie in coming_movies  %}
			<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
				<div class="card">
					<a href="" style="pointer-events: none" class="card__cover">
						<img src="{{coming_movie.poster.url}}" alt="" width="210" height="250">
						<span class="card__play">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg>
						</span>
					</a>
					<div class="card__content">
						<h3 class="card__title"><a href="#"style="pointer-events: none">{{coming_movie.title}}</a></h3>
						<span class="card__category" style="font-weight: bold;">
							{% for genre in  coming_movie.genres.all %}
									<a href="#" style="pointer-events: none">{{genre.name}}</a>
							{% endfor %}
						</span>
						<span style="color: #753750; font-weight: bold;">{{coming_movie.release_date|date:'M  Y'}}</span>
					</div>
				</div>
			</div>
			{% endfor %}
			<!-- end card -->

			

			
		</div>
	</div>
</section>
<!-- end expected premiere -->

{% endblock %}

{% block js %}
<script>
    const wishd_url = "{% url 'series:serie-wish' %}"
        
		function getWishd(id){
            var myHeaders = new Headers()
myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)

    var formData = new FormData()

    formData.append('id', id)

    var requestOptions = {
        method: 'POST',
        headers: myHeaders,
        body: formData,
        redirect: 'follow',
    };

    response = fetch(wishd_url, requestOptions)
        .then(function (response) {

            if (response.ok) {
                response.json().then((data) => {
                    if(data.success){
                        $("#trend-heart-"+id).css('color', 'red')
                    }else{
                        $("#trend-heart-"+id).css('color', 'green')
                    }
                    location.reload(); // Yenileme işlemi
                })
            }
        })
}	




	const wish_url = "{% url 'movies:movie-wish' %}"
        
		function getWish(id){
    var myHeaders = new Headers()
    myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)
    var formData = new FormData()

    formData.append('id', id)

    var requestOptions = {
        method: 'POST',
        headers: myHeaders,
        body: formData,
        redirect: 'follow',
    };

    response = fetch(wish_url, requestOptions)
        .then(function (response) {

            if (response.ok) {
                response.json().then((data) => {
                    if(data.success){
                        $("#trend-heart-"+id).css('color', 'red')
                    }else{
                        $("#trend-heart-"+id).css('color', 'green')
                    }
                    location.reload(); // Yenileme işlemi
                })
            }
        })
}	
</script>
{% endblock  %}