core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include('users.urls'), name="users"),
    path("", include('movies.urls'), name="home"),
    path("", include('tv_series.urls'), name="home"),
    path("api/", include('movies.api.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from .views import *

app_name = "movies"


urlpatterns = [
    path("",show_home, name="home"),
    path("movies/",show_list, name="movies"),
    path("movies-detail/<slug>/",movie_details, name="movies-detail"),
    path('delete-comment/', delete_comment, name='delete_comment'),
    path("movie-wish/",movie_wish_view, name="movie-wish"),
    path("wishlist/",wishlist_view, name="wishlist"),
    path("movie-serie/",movie_serie, name="movie-serie"),
    path('like-movie/<int:comment_id>/',like_comment, name='like_comment'),
    path('dislike-movie/<int:comment_id>/',dislike_comment, name='dislike_comment'),
    
    
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"


urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
    path("change-password/", views.password_change_view, name="change-password"),
    path("reset/", views.reset_password_view, name="reset"),
    path("reset-complete/<slug>/", views.reset_password_complete_view, name="reset-complete"),
    path("activate/<slug>/", views.account_activate_view, name="activate"),
    path("before-reset/",views.before_reset, name="before-reset"),
    path("privacy/",views.show_privacy, name="privacy"),
    path("profile/",views.profile, name="profile"),
    path("plan/",views.plan, name="plan"),
    path("faq/",views.faq, name="faq"),
    path("checkout/",views.checkout, name="checkout")
]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import UserCreationForm as BaseCreationForm
from django.contrib.auth import authenticate
from django.core.mail import send_mail
from django.conf import settings
from services.generator import CodeGenerator
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import check_password
from django.forms.widgets import ClearableFileInput

User = get_user_model()

# -----------------------   Admin Forms  ---------------------------------------------------


class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(required=False,label="Şifrə", widget=forms.PasswordInput)
    password2 = forms.CharField(required=False,
        label="Şifrəni Doğrula", widget=forms.PasswordInput
    )
    email = forms.EmailField(required=False,label='Email')
    full_name =forms.CharField(required=False,label='Ad Soyad')
    username =forms.CharField(required=False,label='İstifadəçi Adı')

    class Meta:
        model = User
        fields = [
            "email",
            "full_name",
            "username",
            "password1",
            "password2",
        ]

    def clean(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        email = self.cleaned_data.get("email")
        full_name = self.cleaned_data.get("full_name")
        username = self.cleaned_data.get("username")
        if password1 and password2 and password1 != password2:
            self.add_error('password1',"Sifreler eyni deyil")
        elif User.objects.filter(email=email).exists():
            self.add_error('email',"Bu email artıq qeydiyyatdan keçib.")
        elif User.objects.filter(username=username).exists():
            self.add_error('username',"Bu istifadəçi adı artıq mövcuddur.")
        elif full_name=="":
            self.add_error('full_name',"Ad boş qoyula bilməz")
        elif any(char.isdigit() for char in full_name):
            self.add_error('full_name',"Ad rəqəmdən ibarət olmamalıdır")
        elif email=="":
            self.add_error('email',"Email boş qoyula bilməz")
        elif username=="":
            self.add_error('username',"İstifadəçi adı boş qoyula bilməz")
        elif password1=="":
            self.add_error('password1',"Şifrə boş qoyula bilməz")       
        elif password2=="":
            self.add_error('password2',"Şifrə boş qoyula bilməz")
        elif len(password1.strip()) < 6:
            self.add_error('password1',"Şifrənin uzunluğu 6 dan böyük olmalıdır")   

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = [
            "email",
            "full_name",
            "is_active",
            "is_superuser",
            "password",
        ]

    def clean_password(self):
        return self.initial["password"]




# Login Form

class LoginForm(forms.ModelForm):
    password = forms.CharField(label="Şifrə", widget=forms.PasswordInput,required=False)
    email = forms.EmailField(required=False,label='Email')

    class Meta:
        model = User
        fields = ("email", "password")


    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if User.objects.filter(email=email):
            user=User.objects.get(email=email)
            check_passwordr=check_password(password,user.password)
            if password=="":
                self.add_error('password',"Şifrə boş qoyula bilməz!")
            elif check_passwordr:
                if not user.is_active:
                    self.add_error('email', "Bu istifadəçi aktiv deyil...")
            else:
                self.add_error('email',"Email və ya Şifrə yanlışdır")

        elif email=="":
            self.add_error('email',"Email boş qoyula bilməz!")

        
            
        else:
            self.add_error('email',"Email və ya Şifrə yanlışdır")
        return self.cleaned_data


       

        
       


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'placeholder': f'{self.fields[field].label}',
                'style':
                 ' text-align:left; padding:15px 40px; background-color:#2b2b31; border-radius: 4px; border: 1px; color: #fff; height: 50px; font-size: 16px; width: 100%;',
            })


class RegisterForm(UserAdminCreationForm):

    def save(self, commit=True):
        user = super(RegisterForm, self).save()
        user.set_password(self.cleaned_data.get("password1"))
        user.is_active = False
        user.activation_code = CodeGenerator.create_activation_link_code(
            size=4, model_=User
        )
        if commit:
            user.save()

        message = f"Please write code below: \n{user.activation_code}"

        # send mail
        send_mail(
            'Activate email', # subject
            message, # message
            settings.EMAIL_HOST_USER, # from email
            [user.email], # to mail list
            fail_silently=False,
        )
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'placeholder': f'{self.fields[field].label}',
                'style':
                 ' text-align:left; padding:15px 40px; background-color:#2b2b31; border-radius: 4px; border: 1px; color: #fff; height: 50px; font-size: 16px; width: 100%;',
            })



class ActivateForm(forms.ModelForm):
    activation_code = forms.CharField(required=False,label='Code')
    class Meta:
        model = User
        fields = ("activation_code", )

    def save(self, user):
        activation_code = self.cleaned_data.get("activation_code")
        if activation_code == user.activation_code:
            user.is_active = True
            user.activation_code = None
            user.save()
        
            
        return user

    def clean(self):
        activation_code = self.cleaned_data.get("activation_code")
        if activation_code=="":
            self.add_error('activation_code'," Boş qoyula bilməz!")
        elif not User.objects.filter(activation_code=activation_code).exists():
            self.add_error('activation_code'," Email və ya şifrə yanlışdır...")

        
        
        

       
        return self.cleaned_data


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'placeholder': f'{self.fields[field].label}',
                'style':
                 ' text-align:left; padding:15px 40px; background-color:#2b2b31; border-radius: 4px; border: 1px; color: #fff; height: 50px; font-size: 16px; width: 100%;',
            })



class CustomPasswordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'placeholder': f'{self.fields[field].label}',
                'style':
                 ' text-align:left; padding:15px 40px; background-color:#2b2b31; border-radius: 4px; border: 1px; color: #fff; height: 50px; font-size: 16px; width: 100%;',
            })



class ResetPasswordForm(forms.ModelForm):
    email = forms.EmailField(required=False,label='Email')
    class Meta:
        model = User
        fields = ("email", )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'placeholder': f'{self.fields[field].label}',
                'style':
                 ' text-align:left; padding:15px 40px; background-color:#2b2b31; border-radius: 4px; border: 1px; color: #fff; height: 50px; font-size: 16px; width: 100%;',
            })

    def clean(self):
        email = self.cleaned_data.get("email")
        if email=="":
            self.add_error('email',"Email boş qoyula bilməz!")

        elif not User.objects.filter(email=email).exists():
            self.add_error('email',"Belə istifadəçi movcud deyil")
        

        

        return self.cleaned_data



class ResetPasswordCompleteForm(forms.ModelForm):
    password1 = forms.CharField(required=False,label="Şifrə", widget=forms.PasswordInput)
    password2 = forms.CharField(required=False,label="Şifrəni Doğrula", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'placeholder': f'{self.fields[field].label}',
                'style':
                 ' text-align:left; padding:15px 40px; background-color:#2b2b31; border-radius: 4px; border: 1px; color: #fff; height: 50px; font-size: 16px; width: 100%;',
            })


    def clean(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1=="":
            self.add_error('password1',"Şifrə boş qoyula bilməz!")

        elif password2=="":
            self.add_error('password2',"Şifrə boş qoyula bilməz!")

users/views.py
from django.shortcuts import render
from .models import MyUser

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model, authenticate, login, logout
from .forms import (
    LoginForm, RegisterForm, ActivateForm, CustomPasswordChangeForm,
    ResetPasswordForm, ResetPasswordCompleteForm,UserDataChangeForm
)
from django.contrib.auth.decorators import login_required
from .decorators import not_authorized_user
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.

User = get_user_model()

@not_authorized_user
def login_view(request):
    next = request.GET.get("next", None)
    form = LoginForm()

    if request.method == "POST":
        form = LoginForm(request.POST or None)

        if form.is_valid():

            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(email=email, password=password)
            login(request, user)
            if next:
                return redirect(next)
            return redirect('/')

    context = {
        "form": form
    }
    return render(request,"users/login.html", context)


def logout_view(request):
    logout(request)
    return redirect('/')


def register_view(request):
    form = RegisterForm()

    if request.method == "POST":
        form = RegisterForm(request.POST or None)

        if form.is_valid():
            user = form.save()

            return redirect("users:activate", slug=user.slug)

    context = {
        "form": form
    }
    return render(request, "users/register.html", context)



def account_activate_view(request, slug):
    user = get_object_or_404(User, slug=slug)
    form = ActivateForm()

    if request.method == "POST":
        form = ActivateForm(request.POST or None)

        if form.is_valid():
            form.save(user=user)
            return redirect('users:login')


    context = {
        "form": form
    }
    return render(request, "users/activate.html", context)

@login_required(login_url='/users/login/')
def password_change_view(request):
    form = CustomPasswordChangeForm(user=request.user)

    if request.method == "POST":
        form = CustomPasswordChangeForm(user=request.user, data=request.POST)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('//')

    context = {
        "form": form
    }
    return render(request, "users/password_change.html", context)



def reset_password_view(request):
    form = ResetPasswordForm()

    if request.method == "POST":
        form = ResetPasswordForm(request.POST or None)

        if form.is_valid():
            email = form.cleaned_data.get("email")
            user = User.objects.get(email=email)

            link = request.build_absolute_uri(reverse_lazy("users:reset-complete", kwargs={"slug": user.slug}))
            message = f"Please click the link below \n{link}"


            # send mail
            send_mail(
                'Reset password',  # subject
                message,  # message
                settings.EMAIL_HOST_USER,  # from email
                [email],  # to mail list
                fail_silently=False,
            )

            return redirect("/users/before-reset/")

    context = {
        "form": form
    }
    return render(request, "users/reset.html", context)



def reset_password_complete_view(request, slug):
    user = get_object_or_404(User, slug=slug)
    form = ResetPasswordCompleteForm(instance=user)

    if request.method == "POST":

        form = ResetPasswordCompleteForm(instance=user, data=request.POST)

        if form.is_valid():
            form.save()
            return redirect("/users/login/")

    context = {
        "form": form
    }
    return render(request, 'users/reset_complete.html', context)





def before_reset(request):
    return render(request,'users/before_reset.html',{})





def show_privacy(request):
    return render(request, 'users/privacy.html',{})


def profile(request):
    profiles = User.objects.all()
    if request.method == 'POST':
        form = UserDataChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/users/profile')
      
    else:
        form = UserDataChangeForm(instance=request.user)

    return render(request, 'users/profile.html',{'form': form,'profiles':profiles})



def plan(request):
    return render(request,'users/pricing.html',{})

def faq(request):
    return render(request,'users/faq.html',{})
    


@login_required(login_url='/users/login/')
def checkout(request):
    if request.method == 'POST':
        payment_plan = request.POST.get('payment_plan', None)
        
        if payment_plan:
            user = User.objects.get(id=request.user.id)
            if payment_plan == 'Basic':
                user.account = 'Basic'
            elif payment_plan == 'Premium':
                user.account = 'Premium'
            user.save()
            messages.success(request, 'Odenis ugurla tamamlandi ')
            return redirect('movies:home')
    return render(request, 'users/payment.html', {})

templates/users/login.html
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from flixgo.volkovdesign.com/main/signin.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 16 Mar 2023 09:50:15 GMT -->
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- CSS -->
	<link rel="stylesheet" href="/static/assets/css/bootstrap-reboot.min.css">
	<link rel="stylesheet" href="/static/assets/css/bootstrap-grid.min.css">
	<link rel="stylesheet" href="/static/assets/css/owl.carousel.min.css">
	<link rel="stylesheet" href="/static/assets/css/jquery.mCustomScrollbar.min.css">
	<link rel="stylesheet" href="/static/assets/css/nouislider.min.css">
	<link rel="stylesheet" href="/static/assets/css/plyr.css">
	<link rel="stylesheet" href="/static/assets/css/photoswipe.css">
	<link rel="stylesheet" href="/static/assets/css/default-skin.css">
	<link rel="stylesheet" href="/static/assets/css/main.css">

	<!-- Favicons -->
	<link rel="icon" type="image/png" href="/static/assets/icon/favicon-32x32.png" sizes="32x32">
	<link rel="apple-touch-icon" href="/static/assets/icon/favicon-32x32.png">

	<meta name="description" content="Online Movies, TV Shows & Cinema HTML Template">
	<meta name="keywords" content="">
	<meta name="author" content="Dmitry Volkov">
	<title>FlixGo – Online Movies, TV Shows & Cinema HTML Template</title>

</head>
<body class="body">

<div class="sign section--bg" data-bg="/static/assets/img/section/section.jpg">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="sign__content">
					<!-- authorization form -->
					{% comment %} <form method="POST" class="sign__form">
						{% csrf_token %}
						<a href="index.html" class="sign__logo">
							<img src="/static/assets/img/logo.svg" alt="">
						</a>
						
						
						<div class="sign__group">
							{% if form.email.errors %}
								{% for error  in form.email.errors %}
								<li style='color:red;'>
									{{error|escape}}
								</li>
								{% endfor %}
							{% endif %}
							
								
								{{form.email}}
							
						</div>

						<div class="sign__group">
							 
								{{form.password}}

								{% if form.password.errors %}
								{% for error  in form.password.errors %}
								<li style='color:red;'>
									{{error|escape}}
								</li>
								{% endfor %}
							{% endif %}
						</div>

						<div class="sign__group sign__group--checkbox">
							<input id="remember" name="remember" type="checkbox" checked="checked">
							<label for="remember"> Məni Xatırla</label>
						</div>
						
						<button class="sign__btn" type="submit">Giriş</button>

						<span class="sign__text">Hesabınız yoxdur? <a href="{% url 'users:register' %}">  Qeydiyyat</a></span>

						<span class="sign__text"><a href="{% url 'users:reset' %}">Şifrəmi unutdum</a></span>
					</form> {% endcomment %}
					<!-- end authorization form -->

					<form method="POST" class="sign__form">
						{% csrf_token %}
						<a href="{% url 'movies:home' %}" class="sign__logo">
							<span style="color: floralwhite; font-weight: bold;font-size: 30px;">Flix</span><span style="color: #18759f;font-weight: bold;font-size: 30px;">Go</span>
						</a>
					
						<div class="sign__group">
							{% if form.email.errors %}
								{% for error  in form.email.errors %}
								<li style='color:red;'>
									{{error|escape}}
								</li>
								{% endfor %}
							{% endif %}
					
							{{form.email}}
					
						</div>
					
						<div class="sign__group">
					
							{{form.password}}
					
							{% if form.password.errors %}
								{% for error  in form.password.errors %}
								<li style='color:red;'>
									{{error|escape}}
								</li>
								{% endfor %}
							{% endif %}
						</div>
					
						<div class="sign__group sign__group--checkbox">
							<input id="remember" name="remember" type="checkbox"  request.COOKIES.remember_me checked="checked" >
							<label for="remember">Məni Xatırla</label>
						</div>
					
						<button class="sign__btn" type="submit">Giriş</button>
					
						<span class="sign__text">Hesabınız yoxdur? <a href="{% url 'users:register' %}">  Qeydiyyat</a></span>
					
						<span class="sign__text"><a href="{% url 'users:reset' %}">Şifrəmi unutdum</a></span>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
    // Set checkbox value from cookie
    if (document.getElementById("remember").checked) {
        document.getElementById("remember").value = "true";
    }
    document.getElementById("remember").addEventListener("click", function() {
        // Set cookie to remember checkbox value
        document.cookie = "remember_me=" + this.checked + "; path=/";
    });
</script>


<!-- JS -->
<script src="/static/assets/js/jquery-3.6.0.min.js"></script>
<script src="/static/assets/js/bootstrap.bundle.min.js"></script>
<script src="/static/assets/js/owl.carousel.min.js"></script>
<script src="/static/assets/js/jquery.mousewheel.min.js"></script>
<script src="/static/assets/js/jquery.mCustomScrollbar.min.js"></script>
<script src="/static/assets/js/wNumb.js"></script>
<script src="/static/assets/js/nouislider.min.js"></script>
<script src="/static/assets/js/plyr.min.js"></script>
<script src="/static/assets/js/jquery.morelines.min.js"></script>
<script src="/static/assets/js/photoswipe.min.js"></script>
<script src="/static/assets/js/photoswipe-ui-default.min.js"></script>
<script src="/static/assets/js/main.js"></script>
</body>

<!-- Mirrored from flixgo.volkovdesign.com/main/signin.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 16 Mar 2023 09:50:15 GMT -->
</html>

templates/users/profile.html
{% extends 'base.html' %}
{% block body  %}


<!-- page title -->
<section class="section section--first section--bg" data-bg="img/section/section.jpg">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="section__wrap">
					<!-- section title -->
					<h1 class="section__title">My FlixGo</h1>
					<!-- end section title -->

					<!-- breadcrumb -->
					<ul class="breadcrumb">
						<li class="breadcrumb__item"><a href="index.html">Home</a></li>
						<li class="breadcrumb__item breadcrumb__item--active">Profile</li>
					</ul>
					<!-- end breadcrumb -->
				</div>
			</div>
		</div>
	</div>
</section>
<!-- end page title -->

<!-- content -->
<div class="content">
	<!-- profile -->
	<div class="profile">
		<div class="container">
			<div class="row">
				
				
				<div class="col-12">
					
					<div class="profile__content">
							
						
						<div class="profile__user">
							
							<div class="profile__avatar">
								{% if request.user.logo %}
								<img src="{{request.user.logo.url}}" alt="">
								{% else %}
								<h3>logo yoxdur</h3>
								{% endif %}
								
							</div>
							
							
							
							
							<div class="profile__meta">
								<h3>Username</h3>
								<span>{{request.user.username}}</span>
							</div>
							
							
							
							
							
							
						</div>
						

						<!-- content tabs nav -->
						<ul class="nav nav-tabs content__tabs content__tabs--profile" id="content__tabs" role="tablist">
							<li class="nav-item" role="presentation">
								<a class="nav-link active" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Profile</a>
							</li>

							<li class="nav-item" role="presentation">
								<a class="nav-link" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">Subscription</a>
							</li>

							
						</ul>
						<!-- end content tabs nav -->

						<!-- content mobile tabs nav -->
						<div class="content__mobile-tabs content__mobile-tabs--profile" id="content__mobile-tabs">
							<div class="content__mobile-tabs-btn dropdown-toggle" role="navigation" id="mobile-tabs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<input type="button" value="Profile">
								<span></span>
							</div>

							<div class="content__mobile-tabs-menu dropdown-menu" aria-labelledby="mobile-tabs">
								<ul class="nav nav-tabs" role="tablist">
									<li class="nav-item"><a class="nav-link active" id="1-tab" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Profile</a></li>

									<li class="nav-item"><a class="nav-link" id="2-tab" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">Subscription</a></li>

									
								</ul>
							</div>
						</div>
						<!-- end content mobile tabs nav -->

						<a href="{% url 'users:logout' %}" class="profile__logout" type="button">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M4,12a1,1,0,0,0,1,1h7.59l-2.3,2.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0l4-4a1,1,0,0,0,.21-.33,1,1,0,0,0,0-.76,1,1,0,0,0-.21-.33l-4-4a1,1,0,1,0-1.42,1.42L12.59,11H5A1,1,0,0,0,4,12ZM17,2H7A3,3,0,0,0,4,5V8A1,1,0,0,0,6,8V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V19a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V16a1,1,0,0,0-2,0v3a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V5A3,3,0,0,0,17,2Z"/></svg>
							<span>Logout</span>
						</a>
					</div>
					
				</div>
				
				
			</div>
		</div>
	</div>
	<!-- end profile -->

	<div class="container">
		<!-- content tabs -->
		<div class="tab-content" id="myTabContent">
			<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab">
				<div class="row row--grid">
					<!-- details form -->
					
					<div class="col-6 col-lg-12 col-sm-4">
						<form method="POST" action="#" enctype="multipart/form-data" class="profile__form">
							{% csrf_token %}
							<div class="row">	
								<div class="col-12">
									<h4 class="profile__title">Profile details</h4>
								</div>

								<div class="col-12 col-md-6 col-lg-12 col-xl-6">
									<div class="profile__group">
										 <label class="profile__label" for="username">Email</label>
										<!-- <input id="username" type="text" name="username" class="profile__input" placeholder="User 123"> -->
											{{form.email}}
									</div>
								</div>

								<div class="col-12 col-md-6 col-lg-12 col-xl-6">
									<div class="profile__group">
										<label class="profile__label" for="logo">Istifadeci Adi</label>
										{{form.username}}
									</div>
								</div>

								<div class="col-12 col-md-6 col-lg-12 col-xl-6">
									<div class="profile__group">
										<label class="profile__label" for="logo">Ad Soyad</label>
										{{form.full_name}}
									</div>
								</div>

								<div class="col-12 col-md-6 col-lg-12 col-xl-6">
									<div class="profile__group">
										<!-- {{form.logo}} -->

										 <label class="profile__label" for="logo">Logo</label>
										<input id="username" type="file" name="logo" class="profile__input" accept="image/*" > 
									</div>
								</div>
								

								<div class="col-12">
									<button class="profile__btn" type="submit">Save</button>
								</div>
							</div>
						</form>
					</div>
					 
					<!-- end details form -->
				

					

					
				</div>
			</div>

			<div class="tab-pane fade" id="tab-2" role="tabpanel" aria-labelledby="2-tab">
				<div class="row row--grid">
					<!-- price -->
					<div class="col-12 col-md-6 order-md-1 col-lg-4 order-lg-1">
						<div class="price price--profile">
							<div class="price__item price__item--first"><span>Basic</span> <span>Free</span></div>
							<div class="price__item"><span>7 days</span></div>
							<div class="price__item"><span>720p Resolution</span></div>
							<div class="price__item"><span>Limited Availability</span></div>
							<div class="price__item"><span>Desktop Only</span></div>
							<div class="price__item"><span>Limited Support</span></div>
							<a href="#" class="price__btn">Choose Plan</a>
						</div>
					</div>
					<!-- end price -->

					<!-- price -->
					<div class="col-12 order-md-3 col-lg-4 order-lg-2">
						<div class="price price--profile price--premium">
							<div class="price__item price__item--first"><span>Premium</span> <span>$19.99</span></div>
							<div class="price__item"><span>1 Month</span></div>
							<div class="price__item"><span>Full HD</span></div>
							<div class="price__item"><span>Lifetime Availability</span></div>
							<div class="price__item"><span>TV & Desktop</span></div>
							<div class="price__item"><span>24/7 Support</span></div>
							<a href="#" class="price__btn">Choose Plan</a>
						</div>
					</div>
					<!-- end price -->

					<!-- price -->
					<div class="col-12 col-md-6 order-md-2 col-lg-4 order-lg-3">
						<div class="price price--profile">
							<div class="price__item price__item--first"><span>Cinematic</span> <span>$39.99</span></div>
							<div class="price__item"><span>2 Months</span></div>
							<div class="price__item"><span>Ultra HD</span></div>
							<div class="price__item"><span>Lifetime Availability</span></div>
							<div class="price__item"><span>Any Device</span></div>
							<div class="price__item"><span>24/7 Support</span></div>
							<a href="#" class="price__btn">Choose Plan</a>
						</div>
					</div>
					<!-- end price -->
				</div>
			</div>

			
		</div>
		<!-- end content tabs -->
	</div>
</div>
<!-- end content -->

{% endblock %}